apiVersion: v1
kind: Service
metadata:
  name: datetime-service
spec:
  type: LoadBalancer  # Exposes the service externally (WAN)
  selector:
    app: datetime
  ports:
   - protocol: TCP
     port: 80         # Exposed port outside the cluster
     targetPort: 8080 # Port your app listens on inside the pods